### ISSUE TITLE
[QUESTION] Order of relationship

### ISSUE THREAD

**Issue by ElGigi** [atlasphp/Atlas.Mapper#6]
Hi,

How we can order the relationship ?

Example, if a have a "project" and associates "tasks", and each "task" has priority value.
I give tasks to project with 'with()' method, but I am unable to order the tasks by a column name.In Realtionship objects, i am able to filter with where with method '\Atlas\Mapper\Relationship\Relationship::where' but not ordering.

Thanks.

**Comment by froschdesign** [comment]
@ElGigi 
I think this topic is covered in the documentation: http://atlasphp.io/cassini/orm/reading.html#1-1-3-4-1

**Comment by ElGigi** [comment]
Thanks @froschdesign 
In my case, i use Mapper with Transit, and the method \Atlas\Transit\TransitSelect::fetchDomain() who extends \Atlas\Mapper\MapperSelect.

Perhaps transfer parameters of method fetchDomain to the fetch methods of MapperSelect ?

**Comment by froschdesign** [comment]
@ElGigi 
> In my case, i use Mapper with Transit…

…and this information is missing in your issue description!

> Perhaps transfer parameters of method fetchDomain to the fetch methods of MapperSelect ?

I would check `TaskEvents::modifySelect()` before. (http://atlasphp.io/cassini/orm/events.html)
