### ISSUE TITLE
Option to always include the related table in a 'with' for a oneToOne relationship

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Mapper#8]
Hello :)

I have a few oneToOne table relationships where I always want the related data. Rather than having to remember to 'with' the related table each time, it would be nice to be able to specify when defining the relationship that the related table data is always fetched.

Alternatively, is there a recommended way to catch and modify the underlying calls to inject an additional 'with' in a custom subclass somewhere?

I'm not sure if here or the Orm repo is the best place for this issue / question / feature request but I figured I'd try here first :)

Thanks!

**Comment by jelofson** [comment]
Here is an option:
There are assumptions in there...

```php
$mapper = $atlas->mapper(Foo::class);
$relationships = $mapper->getRelationships();
$with = [];
foreach (array_keys($relationships->getFields()) as $field) {
    if (get_class($relationships->get($field)) == 'Atlas\Mapper\Relationship\OneToOne') {
        $with[] = $field;
    }
}
        
$record = $atlas->fetchRecord(Foo::class, $id, $with);
```
Or something like that anyway....

**Comment by far-blue** [comment]
Thanks for the answer. I did end up doing something very similar but rather than adding all OneToOne relationships as I think your sample code does I instead have a method to specify an array of field names that get appended to the 'with'. I do think it would be a nice official feature but I'm happy with my app-specific code :)
